name:                crapweb
version:             0.1.0.0
github:              "githubuser/crapweb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

default-extensions:
- DataKinds
- TypeOperators
- OverloadedStrings
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crapweb#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - acid-state
    - mtl
    - text
    - time
    - containers
    - safecopy
    - lens
executables:
  crapweb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crapweb
    - servant-server
    - warp
    - blaze-html
    - servant-blaze
    - containers
    - digestive-functors
    - digestive-functors-blaze
    - text
    - lens
    - time
    - email-validate
tests:
  crapweb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crapweb
